### ISSUE TITLE
How to pass the matrix generated by pyglm to opengl functioins

### ISSUE THREAD

**Issue by GNHua** [Zuzu-Typ/PyGLM#1]
Thanks for this library. I have been waiting for it for almost 2 years. Great work. 

But I do have a question about how to use it. 

Before I found this library, I use numpy and just pass `ndarray` to functions in PyOpenGL, like `glUniformMatrix4fv`. 

Do I need to convert the glm data types before giving them to these functions?

**Comment by Zuzu-Typ** [comment]
Hi GNHua,

I've spent a lot of time trying to improve PyGLM's performance instead of adding new features, because it only offers ~10% of numpy's performance. Unfortunately I haven't really found any solutions yet.

You can now use ```glm.value_ptr(x)``` to pass a matrix to PyOpenGL.
Example: 
```glBufferData(GL_UNIFORM_BUFFER, glm.sizeof(glm.mat4), glm.value_ptr(projectionView), GL_DYNAMIC_DRAW)```

**Comment by GNHua** [comment]
Thanks for your reply.

It is no surprise Numpy is faster, since it is written in C. I am not an expert on this subject, but I wonder whether it makes more sense to build a python binding for the original glm c++ code.

**Comment by Zuzu-Typ** [comment]
So.. 
I now have a C-API version of PyGLM in the making, which (according to some very quick tests) is about 3 times as fast as numpy and will be more than 10 times as fast as current PyGLM.
The basic types (vec2 - 4, mat2x2 - 4x4) are finished and some of the glm::detail functions are finished as well, however, there are probably a bunch of errors in the code that will result in python crashing without throwing an exception, or silent errors, such as wrong results of arithmetic functions.

If you wish to try it out (and are not a Linux user, because I wasn't able to build for Linux yet), you can download the appropriate .pyd file (which can be imported using ```import glm```) from ```/src/build/lib.win<ARCHITECTURE>-<PY-VERSION>```.

You won't be able to do a lot with it though ;)

**Comment by Zuzu-Typ** [comment]
Introduced by https://github.com/Zuzu-Typ/PyGLM/commit/81cb35df863c553930e51a172cea50dd69fcc2ea .
