### ISSUE TITLE
glm array views

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#104]
Hello,
Would it be possible to create a second `glm.array` type, or to change the array behavior to allow to use them as array views ?

The purpose of it is to improve the efficiency in manipulation of such arrays, as well as allowing to implement a sort of dynamix list behavior on the top of it:

```python
# lookup in a buffer
glm.array(nparray)[n]  -> vec3     # this is currently copying the array then extracting the interesting point, the copy could be avoided.

# managing the array
a = glm.array(...)
glm.array(a[:n] + a[m:])  # this is currently copying the slices of a into separated arrays, then put into the new one, the separated arrays could be avoided.
```

So as a memory view, such a new type would likely reference the viewed object to not loose the ownership of the data. Maybe the best option could be to pack this into the current glm.array type and use `bytearray` as allocator providing the viewed object for newly created arrays.

I think this wouldn't be a huge modification of the array class since it already supports the buffer protocol and therefore is already able to check for the buffers it's copying at creation. Instead I imagine it would be simple to check the buffer and just reference it.

**Comment by Zuzu-Typ** [comment]
Hi Jimy,

I thought about adding this myself. Especially for slices, as slices would usually be expected to be references.
There are a couple of things to consider though.

The reason I originally decided to go with copies rather than references was to have the same behaviour for whatever input values the `glm.array()` constructor is supplied with, as for most instances, it is simply impossible or unreasonable to use references. 
Of course, for some types, such as glm's or numpy's arrays, the reference approach is much faster and also allows for data manipulation between different types of arrays - which can be a good thing, but also a bad thing, if it is not obvious that it is happening.

I think the best option would be to have a static method that allows for reference initialization, e.g. `from_reference` or `as_reference`. I'm not sure which would be the more logical choice. This would also be a lot faster, since the general init function has to check whether it's a vec, mat, quat, ... etc. first before checking if it's an array or buffer protocol type.

Another thing to consider is that this would only work for buffer objects that have the same memory layout as glm's arrays (which numpy arrays do).
And there is also the possibility that the buffer is `readonly`. Which would either require me to use a copy of the buffer as I do now, or add a readonly field that I check before modifying the buffer.

So as you can see, there are a lot of critical design choices to make here and I haven't made my final decisions yet.
But it's definitely coming in a future update (most likely the one I'm currently working on, which enhances the array's features).

Cheers,
--Zuzu_Typ--

**Comment by jimy-byerley** [comment]
view and readonly flag ... It's beginning to resemble to numpy ;)
It reminds me a [mine project](https://github.com/jimy-byerley/numcy/) I put in reserve for when I will have time, which is why I asked you if it was possible to [mix glm with cython](https://github.com/Zuzu-Typ/PyGLM/issues/93).

Anyway, maybe a solution could be to
- have always a copy using the default constructor, so the behavior is easy to predict
- have a staticmethod `frombuffer(buff)` or `view(buff)` creating an array with a reference
- have 2 array types, one for readonly with no modification method implemented and one with full implementation

Just as an idea of course.

**Comment by Zuzu-Typ** [comment]
Okay, it should generally work now, with the added `as_reference` method.
It does not work however, if the given buffer does not have the same shape as glm's arrays do (which have a very odd shape for matrices, because for some reason glm has column major order ..).
It will issue a warning if a copy is created instead of a reference.
Otherwise you can also check the `reference` member of the resulting array instance, which reveals whether or not the array has a reference or not.

I also added a lot more useful functions (such as `sort`, `map` and `filter`) and switched from using `+` and `*` as concat and repeat to using them as numeric operations (also adding a lot more of those).

Cheers,
--Zuzu_Typ--

**Comment by jimy-byerley** [comment]
great ! thanks !
