### ISSUE TITLE
PyGLM not working with Python 3.8.2

### ISSUE THREAD

**Issue by TristanM42** [Zuzu-Typ/PyGLM#105]
Hello,

i tried installing PyGLM for Python 3.8.2 : `py -3.8 -m pip install pyglm` 
Installation seems successful at first, but after i import glm, i get an error while trying to access anything : for example, glm.vec3, mat4, ...

Doing dir(glm) only print this : `['NimPyException', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_glm', 'dump', 'dumps', 'load', 'loads', 'version']`

So i guess installation failed or something is missing. Also, pip list gave me glm version 1.99.3, but glm.__version__ returns v0.4.3. Finally, I also installed pyglm version for Python 3.6.0 (so pyglm 1.1.8) and glm is working ! However, i need glm to be working with Python 3.8.

I hope i was clear enough, thank you in advance for help.

Tristan

**Comment by Zuzu-Typ** [comment]
Hi there,

it appears that whichever module it is you're importing, it's not PyGLM.
There are more modules out there which use the same import name, so I'm guessing you've imported one of those.
You can tell by running 
```Python
>>> import glm
>>> glm # (actually PyGLM)
<module 'glm' from 'C:\\Python38-32\\lib\\site-packages\\glm.cp38-win32.pyd'>
```
PyGLM does not have a `__version__` field. Also there is no version 0.4.3, only [0.4.3b1](https://github.com/Zuzu-Typ/PyGLM/wiki/Version-history#043b1), which isn't even available for Python 3.7 or greater.

Maybe you are making a relative import by mistake, because there is a folder called glm or something of that sort.

Cheers
--Zuzu_Typ--

**Comment by TristanM42** [comment]
Thank you, I must had a previous version which overrided the pyglm package or idk... from an old mistake i made a long time ago is guess. I tried uninstalled and it didn't change anything, but now it's working... i might be tired maybe, sorry for the inconvenience.

**Comment by Zuzu-Typ** [comment]
Don't worry about it. I'm glad you were able to solve it (:
