### ISSUE TITLE
How can I use this library in pypy

### ISSUE THREAD

**Issue by littlefish12345** [Zuzu-Typ/PyGLM#106]
I use pypy37-pp73.
I tried to compile it with source code and it didn't pass.Even with pip it didn't work too.
Then I try to use the pre-compiled whl file for cp37.It can be installer after I modified its file name but it can't work either.
So how can I do?

**Comment by Zuzu-Typ** [comment]
Hi there,

well, it's no wonder you didn't get it to work, because C-API Extension modules for CPython (e.g. PyGLM) are not compatible with PyPy, since PyPy's whole deal ist that it doesn't work like CPython under the hood.

There is no way around this either. You'd have to completely recreate PyGLM for PyPy.

The only thing you could do is use a very very old and highly limited [version](https://github.com/Zuzu-Typ/PyGLM/wiki/Version-history#021a1) of PyGLM, back when it was still written in pure Python.

Cheers
--Zuzu_Typ--
