### ISSUE TITLE
rotate(mat3 , angle) not found

### ISSUE THREAD

**Issue by radiocold** [Zuzu-Typ/PyGLM#107]
I dont found the function "glm.rotate(mat3 , angle)" only I see the function "rotate(m, angle, axis)" but i need for Matrix3x3.  My python is 64 bits

**Comment by Zuzu-Typ** [comment]
Hi there,

yes, this is an issue in the current stable version of PyGLM.
It is already fixed in the latest pre-release though.

It'll probably be a while until Version 2.0.0 is officially released, so I would recommend you to use the latest [pre-release](https://pypi.org/project/PyGLM/2.0.0a2/) if you want to use this feature.

Sorry, I just haven't wrapped up all my changes yet. And Python 3.9 support needs to be dealt with on top of that...

Anyway, thanks for using PyGLM!

Cheers,
--Zuzu_Typ--
