### ISSUE TITLE
binary operator / allow operands type which are not allowed in glsl specifications

### ISSUE THREAD

**Issue by phil-el** [Zuzu-Typ/PyGLM#13]
import glm
glm.mat4(1.0) / glm.vec4(1.0)
tvec4(            1,            1,            1,            1 )

I don't see in the glsl specs where this is allowed, glm.mat4(1.0) * 1.0/glm.vec4(1.0) is well defined but the expression above should raise a TypeError. Did I miss something? or does c++ glm allow that?

**Comment by Zuzu-Typ** [comment]
In glm-0.9.9-a2 (the version PyGLM is based on and still the latest version of GLM) it is defined.
Maybe you overlooked it, because it defines the operations for _row_type_ and _col_type_, which are vectors of course.
![mat4_row_type](https://user-images.githubusercontent.com/20467351/36628072-9989f010-194c-11e8-80b3-944d85f4c49b.PNG)

**Comment by phil-el** [comment]
Ok, I see, I thought glm was trying to be compliant with glsl, a vertex shader like

#version 130
void main() {
  mat4 a = mat4(1.0);
  vec4 b = vec4(1.0);
  vec4 c = a / b;
  gl_Position = vec4(1.0);
}
doesn't compile, I'll have to be a bit careful to not use too much glm extension as I need to be able to move code from cpu <--> gpu
