### ISSUE TITLE
Constructing vectors from bytes not possible for multi-byte types

### ISSUE THREAD

**Issue by leifvan** [Zuzu-Typ/PyGLM#130]
Hi,

first of all thanks for this great package! It helped me a lot for my current project already.

I was reading about the buffer protocol compatibility of the GLM types in the wiki and I tried to convert vector types to and from the binary format. Apart from one-byte integer types (uint8, int8), I am unable to construct vectors from bytes:

```python
vector = glm.u8vec3(1, 2, 3)
as_bytes = bytes(vector)
print(glm.u8vec3(as_bytes))  # prints as expected: "u8vec3(            1,            2,            3 )"
```

but
```python
vector = glm.i16vec3(1, 2, 3)
as_bytes = bytes(vector)
print(glm.i16vec3(as_bytes))  # throws: "TypeError: invalid argument type(s) for vec3()"
```

and also
```python
vector = glm.f32vec3(1, 2, 3)
as_bytes = bytes(vector)
print(glm.f32vec3(as_bytes))  # throws: "TypeError: invalid argument type(s) for vec3()"
```

I also tested this with other vector lengths, but got the same error. Am I missing something here or is it simply not possible to do this for multiple bytes? Thanks in advance!

**Comment by Zuzu-Typ** [comment]
Hi there (: 

You're very welcome!

The reason why it doesn't work is simple, because even the first variant wasn't actually intended. It just happened to be a useful byproduct of the way the buffer protocol works.

In Python, bytes are stored as unsigned characters (i.e. unsigned integers with 8 data bits). That is the same format used by the `u8`-vectors.
Thus, the type check succeeds when a bytes object is passed.

I have contemplated having a `from_bytes` method, but never got around to it. So I guess now would be my call (: 

I'll try to get around to it soon.

Cheers,
--Zuzu_Typ--

**Comment by Zuzu-Typ** [comment]
Okay, this should do the trick.

I had to go for a `to_bytes()` method alongside the `from_bytes()` method, as there would otherwise be problems with matrix types (has to do with the memory layout).

For vector and quaternion types it shouldn't matter though whether you use `bytes(vec)` or `vec.to_bytes()`, aside from performance benefits of the latter.

I'll update the documentation accordingly and push an update afterwards (: 

Cheers,
--Zuzu_Typ--
