### ISSUE TITLE
Memory leak when constructed from numpy array

### ISSUE THREAD

**Issue by flosacca** [Zuzu-Typ/PyGLM#159]
This code piece can cause a memory leak in my computer:

```python
while True:
    glm.vec3(np.zeros(3))
```

In addition, `glm.vec3(*np.zeros(3))` is OK, but `glm.vec3(*np.zeros(3, dtype=np.float32))` also causes the memory leak.

I tested with PyGLM 2.5.3 and NumPy 1.20.2 on Windows 10.

**Comment by Zuzu-Typ** [comment]
Hey there (: 

Thank you very much ^^
You've actually found two different memory leaks.

`glm.vec3(np.zeros(3))` creates a memory leak, because the buffer given by numpy is never released.
`glm.vec3(*np.zeros(3, dtype=np.float32))` leaks, because the number objects (`numpy.float32` objects) aren't properely dereferenced.
Then again, `glm.vec3(*np.zeros(3))` doesn't leak, because it passes Python `float`s to the `vec3` function, instead of numpy floats. And those are handled differently.

Both leaks should be fixed now.

Cheers
--Zuzu_Typ--
