### ISSUE TITLE
Segfault after recovering from TypeError when instantiating objects using a list or tuple of incompatible objects

### ISSUE THREAD

**Issue by esoma** [Zuzu-Typ/PyGLM#169]
```python
import glm
bad_input = ('a', 'b')
try:
    glm.vec2(bad_input)
except TypeError:
    pass
glm.vec2((1, 1)) # <<< segfault
```

The error-ing glm object may be anything (`quat`, `mat`, `vec`). `bad_input` must be either a `tuple` or `list` of the correct size for the object. Only one value in `bad_input` need be bad. Other sequence-like objects (`str`, `bytes`, custom objects with `__len__` and `__iter__` implemented) do not produce the behavior. Error occurs on both linux and windows with 2.5.6. The segfault only occurs when instantiating another object (again of any glm type, it need not be the same as the one that initially caused the `TypeError`) using a `tuple` or `list` that would not cause a `TypeError` (so for example, doing `glm.vec2(0)` will not cause the segfault.

**Comment by Zuzu-Typ** [comment]
Hello there,

what a peculiar error. I had trouble reproducing it at first, because it did _not_ occur when using the DEBUG configuration.

Anyway, I did manage to find the error.
In PyGLM there are [4 `PyGLMTypeInfo` objects](https://github.com/Zuzu-Typ/PyGLM/blob/master/PyGLM/internal_functions/type_checkers.h#L2418-L2427) used to store information about parameters that are tuples / lists / buffers / other iterables.
There are 4 of them, because that's the maximum number required at once (e.g. for 4x4 matrices, when initialized with 4 vectors in tuple form).
In DEBUG configuration these objects are always overwritten when used.
In release configuration they are simply re-initialized (i.e. the [`init`](https://github.com/Zuzu-Typ/PyGLM/blob/master/PyGLM/internal_functions/type_checkers.h#L404) function is called).

To improve performance the `PyGLMTypeInfo` structure has [a field](https://github.com/Zuzu-Typ/PyGLM/blob/master/PyGLM/internal_functions/type_checkers.h#L390) to store the temporary data in (e.g. the `vec2` or `mat4x4`).
When the constructor is called, the [data pointer](https://github.com/Zuzu-Typ/PyGLM/blob/master/PyGLM/internal_functions/type_checkers.h#L392) is set to this field. However, _this doesn't happen when calling `init`._

Now, when passing invalid parameters to a function (like `glm.vec2(bad_input)`) the data pointer is [set to NULL](https://github.com/Zuzu-Typ/PyGLM/blob/master/PyGLM/internal_functions/type_checkers.h#L1536).
Thus, next time we try to store actual data in the buffer, it still points to NULL and we get a segfault.

To fix this, I simply added [a line of code](https://github.com/Zuzu-Typ/PyGLM/commit/bc7dbe38d6e24d1ca96d715086dc9e13ac98ba84#diff-56fc7dddd91264fe072f9f542a26418fc422aef763bfbf29ae799e0446d02d14R2272) that sets the data pointer back to the internal buffer whenever data is supposed to be written to it.

Thanks a lot for finding this (: 

Cheers
--Zuzu_Typ--

**Comment by jimy-byerley** [comment]
Hello ! I'm not sure how, but it's fixing a segfault in arrex I was tracking since 2 weeks :)
Thanks !
