### ISSUE TITLE
Translate function not working??

### ISSUE THREAD

**Issue by nasser225** [Zuzu-Typ/PyGLM#17]
I have this from a tutorial:

vec = glm.vec4(1.0,0.0,0.0,1.0) 
id_matrix = glm.mat4()
trans_matrix = glm.translate(id_matrix, glm.vec4(1.0, 1.0, 0.0))
vec = trans_matrix * vec

printing vec gives 0.0,0.0,0.0 and I was expecting 2.0,1.0,0.0

Please help! Thanks

**Comment by Zuzu-Typ** [comment]
Hi nasser225,
you are indeed correct - the translate() function was not working as intended, however that is actually not the reason why the code above is not functional.
In [gtruc/glm](https://github.com/g-truc/glm) (the original glm) there has been a change to the way matrices are initialized (or rather - they removed the initialization completely) https://github.com/g-truc/glm/commit/4cf8a10af2bba678c2ad136006e6ec41118b6746 .
This results into `glm.mat4()` returning an uninitialized (empty) matrix:
```
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
```
That's why the translation doesn't work.
You have to use `glm.mat4(1.0)` instead.

I'm trying to get gtruc to [revert this change](https://github.com/g-truc/glm/issues/740) (because I ran into the same problem as you did).

**Comment by dwtd** [comment]
I also noticed that translate (and scale) don't seem to be working, but unrelated to the matrix initialization issue you mentioned from the original GLM.  As a simple example:
```python
    M = glm.translate(glm.mat4(1.0), glm.vec3(2.0, 2.0, 2.0))
    print("M:\n{}".format(M))
```
produces:
```
M:
[            1 |            0 |            0 |            0 ]
[            0 |            1 |            0 |            0 ]
[            0 |            0 |            1 |            0 ]
[            0 |            0 |            0 |            1 ]
```

If I change `translate` to `scale` I get:
```
M:
[            0 |            0 |            0 |            0 ]
[            0 |            0 |            0 |            0 ]
[            0 |            0 |            0 |            0 ]
[            0 |            0 |            0 |            1 ]
```

Something here is clearly not right.  For a sanity check, I confirmed that in C++ the translate and scale functions do the right thing, and they do.

**Comment by Zuzu-Typ** [comment]
I accidentally screwed up the macro that generates the two of these functions, resulting in them always using empty arguments.
I'll release a fix soon
