### ISSUE TITLE
Install on raspberry

### ISSUE THREAD

**Issue by Thibault78** [Zuzu-Typ/PyGLM#173]
Hi,
I'm trying to install PyGLM 2.5.7 on a raspberry pi 3 with latest Raspbian image (based on Debian 11) and Python 3.9.2.
However the build fails, ending with a :
  _arm-linux-gnueabihf-gcc:` fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1_

I attach the full log as I may not have pinpointed the right thing...
Any hint or help would be highly appreciated, if installing PyGLM on a raspberry is supposed to be possible
Many thanks!
[log.txt](https://github.com/Zuzu-Typ/PyGLM/files/7709454/log.txt)

**Comment by Zuzu-Typ** [comment]
Hi there,

this is just a wild guess, but I think it might be possible that it just timed out.
If it did run for quite a bit before reporting an error, that would support this hypothesis.

On a Windows PC with good hardware, build times are just a couple of seconds.
On the x86 Linux-machines provided by GitHub Actions, the build time is roughly 3 minutes.
However, the ARM builds (which use x86 Linux-machines that emulate the ARM-architecture) take a little over 30 minutes to build.
Since Raspbian is built for a 32-bit ARM architecture and doesn't have particularly powerful hardware, I suppose it might be a bit on the slow side.
So I suppose at some point the compiler just gives up and reports an error.

This is just a guess though. 


That said though, it seems `piwheels` was [unable to build](https://www.piwheels.org/project/pyglm/) PyGLM as well.
I'll have to look into this a bit more.

**Comment by Thibault78** [comment]
Thank you Zuzu-Typ for your hint. It was a memory issue (dmesg said "out of memory") where the os killed the most demanded process.
I have increased the swap (512MB) and the build succeeds now.
