### ISSUE TITLE
Vectors cannot be constructed from non-c-contiguous numpy arrays

### ISSUE THREAD

**Issue by avdstaaij** [Zuzu-Typ/PyGLM#205]
If a numpy array is not C_CONTIGUOUS, attempting to construct a vector from it raises a TypeError.

To reproduce:
```python3
a = np.array([[1,1],[2,2]])
a = np.transpose(a)
v = ivec2(a[0])
```

This is highly confusing, since in the example above, `a[0]` looks perfectly eligible:
```
>>> a = np.array([1,2])
>>> a
array([1, 2])
>>> ivec2(a)
ivec2( 1, 2 )

>>> a = np.array([[1,1],[2,2]])
>>> a = np.transpose(a)
>>> a[0]
array([1, 2])
>>> ivec2(a[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid argument type(s) for vec()
```

Finding the root of this issue was... not easy. 😅

**Comment by Zuzu-Typ** [comment]
Hmm.. I'm not sure if I'm correct, but I believe the issue is that the given array is not contiguous at all. 
If I'm not mistaken, for a 1-dimensional array, a C-contiguous array is also an F-contiguous array and vice-versa.

Since the given vector contains data that is not stored at consecutive memory addresses, the data is not contiguous.
At least that's what I'm assuming.

PyGLM should support buffer data that isn't contiguous, which it currently doesn't.

I'll check if my assumptions are correct the next time I have access to a computer.

**Comment by avdstaaij** [comment]
> Hmm.. I'm not sure if I'm correct, but I believe the issue is that the given array is not contiguous at all. If I'm not mistaken, for a 1-dimensional array, a C-contiguous array is also an F-contiguous array and vice-versa.

Ah, you're right. I was inspecting the transposed 2D array, which is F-contiguous but not C-contiguous. A row from that array is indeed neither C-contiguous nor F-contiguous.
