### ISSUE TITLE
Provide a decent documentation. 

### ISSUE THREAD

**Issue by xeedness** [Zuzu-Typ/PyGLM#26]
I tried to use the original glm documentation. But since there is about 95% missing in PyGLM, it's not a well working approach. So while I think this is a good project, it's not an option if you have the desire to get something done.

**Comment by Zuzu-Typ** [comment]
I'm planning to create a more 1:1 approach by using a combination of C and C++ and using the original GLM.
It will take a while though..

PyGLM is very close to GLM already.
The only real differences are the restrictions of Python. For example you can't use sizeof() or pointers the same way you would in C++.
Additionally vec1 doesn't exist because I couldn't imagine a use case and implementing the entire type would have generated a whole lot of extra work I wasn't willing to take.
The only thing really 'missing' are the experimental extensions.

What were you having issues with?

**Comment by einarf** [comment]
You can also make a pull request and improve the tiny bit of docs that are already present sharing what you figured out. Most projects do rely on the community to succeede.
