### ISSUE TITLE
Unify str or list bidirectional conversions of vec and mat, also to work with json

### ISSUE THREAD

**Issue by pepcots** [Zuzu-Typ/PyGLM#42]
Is it possible to unify criteria about list and str conversions for mat and vec?

**vec** _(for me, a very good criteria)_
`str(glm.vec3())` returns class representation with values, OK
`list(glm.vec3())` returns a list of values, OK
`json.dumps( list(glm.vec3()))` nice code to convert to json string, OK
`glm.vec3( json.loads( "[1,2,3]"))` nice code to parse a json string, OK

**mat** _(some missig fucntionalities)_
`str(glm.mat3())` returns a formatted string with values (not class representation), OK
`list(glm.mat3())` return a list of mvec3...some times you prefer a list of lists... semi ok...
`[list(mv) for mv in glm.mat3()]` pretty nice code to have a list of lists, OK
`json.dumps([list(mv) for mv in glm.mat3()])` not super nice code, but OK
There is no way to do an inline json.loads from a json string. Is it?

**Comment by Zuzu-Typ** [comment]
There is, however, it's not very pretty.
`glm.mat3(*[i for l in json.loads(mat3_as_string) for i in l])`

Unfortunately the matrix constructors do not support initialisation with iterators, due to massive performance loss (because it would have to check every element in the list and it's sublists on validity and it wouldn't be able to tell lists, arrays, matrices, byte strings and any other iterator apart).

The reason why `list(glm.mat3())` returns a list of `mvec3`s is because otherwise it would be impossible to change the content of the matrix by it's elements.
For example:
```Python
m3 = glm.mat3()
m3[0][0] = 9
print(m3[0][0])
```
We would expect it to print `9`, but it would print the default value `1`, because it could not be changed by the element.
You would have to use `[0, 0]` instead.

I chose to do it the way numpy also does it.

It's simply a design choice.

I could of course add an as_list() and from_list() method to do exactly that.

**Comment by pepcots** [comment]
Thank you for you answering so fast, I really appreciate your long explanation.

I understand why it has been done this way and seems the only way, so, no need to add any method like "as_list()" in the library.

Nice code is a wish, but, robust code is a must.

Many thanks

**Comment by Zuzu-Typ** [comment]
Actually, there's a better way of doing this:
```Python
mat3_as_list = memoryview(glm.mat3()).tolist()
mat3_from_list = glm.mat3(*itertools.chain(*mat3_as_list)) # requires itertools
# or as an alternative way:
mat3_from_list = glm.mat3(*map(glm.vec3, mat3_as_list))
```
