### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by alexcher-im** [Zuzu-Typ/PyGLM#45]
Are you planning to add support for PyPy? It seems that the current version of PyGLM is not compatible with it, I got a lot of compilation errors when trying to install via pip.

**Comment by Zuzu-Typ** [comment]
I've thought about adding support for PyPy, however when I looked into it more, I quickly found out that CPython and PyPy extensions are not really compatible (from what I've read [here](https://morepypy.blogspot.com/2018/09/inside-cpyext-why-emulating-cpython-c.html)).

The way PyPy and CPython are written under the hood is so different that I might have to be required to rewrite the entire library. (which is currently about 36000 lines of code, if you don't count the macros and templates which would expand into about 10 times more lines).

Additionally, I've added a few specific tweaks that greatly increase PyGLMs performance, which (from what I understand) wouldn't be possible in PyPy, due to the way objects are handled.

I've never developed for PyPy, but I could give it a try.
Most likely though, a PyPy version is just not meant to be.

**Comment by Zuzu-Typ** [comment]
I tried to build it myself and couldn't find a way of getting it to run, unfortunately.

If you do not care about performance, you can use a very old version of PyGLM.
Your "best" choice would be [PyGLM 0.2.1a1](https://pypi.org/project/PyGLM/0.2.1a1/), which is the last version written in pure Python (though it uses numpy under the hood) or if you really need to go bare, you have to roll back all the way to [PyGLM 0.1.0a1](https://pypi.org/project/PyGLM/0.1.0a1/), which is the only version that is completely pure Python.
Keep in mind that either way you are going to loose performance as well as feature-completeness.

If you do care about performance, your only chance is to try using [PyGLM 0.4.8a1](https://pypi.org/project/PyGLM/0.4.8b1/), which was the last version written in C, which you might have better luck compiling with.
