### ISSUE TITLE
euclidean appears to use vec2 as arguments instead of vec3

### ISSUE THREAD

**Issue by Cazadorro** [Zuzu-Typ/PyGLM#53]
After attempting to put in a glm.vec3 in glm.euclidean, I was met with an error about it being an invalid argument.  Upon further inspection, it appears that while both [GLM's documentation](https://glm.g-truc.net/0.9.2/api/a00285.html) and text documentation inside of PyGLM.cpp ("euclidean(v) -> vec3\nConvert Polar to Euclidean coordinates.") state that vec3 is the input, the function was generated with a macro that takes only vec2 as input 

    PyGLM_MAKE_GLM_FUNC_V2__tfF(euclidean)

I believe the above should be changed to 

    PyGLM_MAKE_GLM_FUNC_V3__tfF(euclidean)

I don't know if this a coincidence, but neither polar nor euclidean have auto generated python stubs for documentation purposes.  Polar, for example, can be used, but doesn't have anything in `glm/__init__.py` which is generated.

**Comment by Zuzu-Typ** [comment]
I was just as confused as you are when creating the function.
So I just decided to stick to glm's behaviour - after all that's what we're doing here.
Looking at the code, both the [declaration](https://github.com/g-truc/glm/blob/master/glm/gtx/polar_coordinates.hpp) and the [implementation](https://github.com/g-truc/glm/blob/master/glm/gtx/polar_coordinates.inl) take a vec2 argument.

So this is an error on [g-truc/glm](github.com/g-truc/glm)'s side.

> Polar, for example, can be used, but doesn't have anything in glm/__init__.py which is generated.

I'm not sure what you know that I don't, but the last time I looked, glm was a C/C++ extension making it more of a binary DLL file instead of any readable or ordered structure.

**Comment by Cazadorro** [comment]
Huh weird, you are 100% correct, I'll bring this up on the GLM repo.  On the second part,  I don't know how generating the python files works in this process, I know they don't correspond to the actual code, but they are usefull for auto-completion and parameter hints, I figured that __init__.py was autogenerated in the extension processes, because otherwise we don't see those comment strings on our end with out looking at the cpp source.  Right now my IDE thinks those functions don't exist because they don't appear in any python files.
