### ISSUE TITLE
support for experimental extension?

### ISSUE THREAD

**Issue by hschwane** [Zuzu-Typ/PyGLM#68]
Hi, 
are you planning to add support for the experimental extensions (GTX)? I am trying to port a c++ code to python which uses the [glm::decompose function](https://glm.g-truc.net/0.9.8/api/a00204.html).

Also, thanks for this project. Makes my work a lot easier right now. :)

**Comment by Zuzu-Typ** [comment]
Hi there hschwane,

I'm sorry, but porting every single GTX extension over to Python would be way too much effort (especially with the other data types, such as the other int matrices and dual quaternions).
However, implementing single extensions, especially single methods is quite simple in most cases.

I try to port GTX extensions only when requested, because I don't have a lot of time to work on PyGLM these days.

The decompose extension should make it into the next version - which will hopefully be released soon.

Either way, thank you for using my library (:

**Comment by hschwane** [comment]
sure, that would be a lot of work. Totally understandable. Looking forward to the next version. I found a way around using decompose until then, so don't stress yourself ;)
