### ISSUE TITLE
missing conversion fmat <-> dmat

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#72]
Hi,
it's me again.

we can yet convert vectors between simple and double types, for example `fvec3 <-> dvec3` using the constructor:
```python
>>> fvec3(dvec3(1))
vec3( 1, 1, 1 )
```

but the same seems to not exist for matrices:
```python
>>>  fmat4(dmat4(1))
TypeError: invalid argument type(s) for mat4x4()
```
My current solution is to use the constructor from an iterator, such as 
```python
>>> fmat4(*dmat4(1))
```
This way the `dmat4` gives an iterator of python objects, that are used as a sequence of arguments for `fmat4`. But this approach is not efficient nor aesthetic.

Can you possibly implement it ?

**Comment by Zuzu-Typ** [comment]
Hi there Jimy,

yes, I can.
And coincidentally, [I already have](https://github.com/Zuzu-Typ/PyGLM/commit/5bfe562721e06f0ff0f667e823d5e3153730c045).

Feel free to clone the repo, build PyGLM from source and try out the latest version.
The reason why I didn't publicly release it yet, is because I want to test it some more, as I completely changed the way PyGLM determines which argument types it's been passed.
So if your code doesn't run with this version, please tell me so.

Also I'm currently working on an array type that would allow you pass multiple vectors / matrices to other C libraries without having to use NumPy.

Cheers
--Zuzu_Typ--

**Comment by jimy-byerley** [comment]
> Also I'm currently working on an array type that would allow you pass multiple vectors / matrices to other C libraries without having to use NumPy.

Great news ! Is it something like a array.array using the standard list methods but for glm types ?

**Comment by Zuzu-Typ** [comment]
> Is it something like a array.array using the standard list methods but for glm types ?

I'm not too firm on any specifics yet, but it's supposed to be initialized with an argument list of glm types.
It would then copy the content of the individual objects to a buffer.
```Python
#Example (pseudo) code 
arr = glm.array(glm.vec3(1,2,3), glm.vec3(4,5,6), glm.vec3(7,8,9))
print(arr[0]) # -> vec3(1,2,3)
print(list(arr)) # -> [vec3(1,2,3), vec3(4,5,6), vec3(7,8,9)]
print(arr.ptr) # -> ctypes.c_void_p(8517237731)
print(arr.nbytes) # -> 36
```

It's not supposed to be the next big thing or anything, just a container that allows you to pass multiple objects to external C functions.
Maybe it will get more versitile in the future though.

**Comment by jimy-byerley** [comment]
just to notice you: Tested and approved ! no problem in my usecase
(except maybe with cython, i got a precision issue in initializing dvec3 from a cython carray, but i'm not sure ...)
