### ISSUE TITLE
Matrix columns and rows are switched in glm

### ISSUE THREAD

**Issue by Zuzu-Typ** [Zuzu-Typ/PyGLM#73]
I just realized, that glm's matrix classes have a flaw in them.
They create a CxR matrix and not the mathematically correct RxC matrix.

So a normal mat2x4, would have 2 rows and 4 columns, but a glm.mat2x4 has 2 columns and 4 rows instead.
This is especially obvious with the `glm.column()` and `glm.row()` functions, which seem to do the opposite of what they're supposed to, when looking at the output of printing a matrix to the console:
``` Python
>>> m24 = glm.mat2x4(1,2,3,4,5,6,7,8)
>>> print(m24)
[ 1 | 2 | 3 | 4 ]
[ 5 | 6 | 7 | 8 ]

>>> glm.row(m24, 0)
vec2( 1, 5 )

>>> glm.column(m24, 0)
vec4( 1, 2, 3, 4 )
```
I'm not exactly sure how I should face this now, as it will most definitely not be changed in the original glm version.
I could...

1. Not do anything about it at all and try to leave notes about it in documentation
2. Try to swap the order of columns and rows and risk destroying something
3. Change the way matrices are printed to fit the way they're represented by glm
4. ...?

I need some opinions on this before I can decide.

**Comment by jimy-byerley** [comment]
Hi
If I mind,
### prefered way
> 1.  Not do anything about it at all and try to leave notes about it in documentation

It appears to be the most intuitive way to me since GLM is column major in naming, instantiating, indexing, and printing
every glm object is printing columns as text lines: vectors, square matrices, non-square matrices

I think GLM did well by naming matrices with CxR as it also uses it for indexing and display. It brings a lot of coherence.

Maybe a note about this full CxR convention early in the doc would be usefull.

### satisfying alternative
> 2. Try to swap the order of columns and rows and risk destroying something
> 3. Change the way matrices are printed to fit the way they're represented by glm
If you do something, then do the two of them. If the convention is no more full CxR, the only option I find satisfying would be:
- CxR  for indexing and instantiating  (have to be close to the memory implementation, plus it's usefull for some base decomposing tricks). 
   In my mind, index and instantiation are programming concerns
- RxC for naming and printing,  such as names and displays fit the mathematical convention.  
   In my mind, names and display are theoretical concerns

NOTE:
   If you do change the string representation then could you use the '.' as systematic decimal separator ? The GLM implentation is using locales settings I think, and is annoying to use with parsers

**Comment by Zuzu-Typ** [comment]
Hi Jimy,

thank you for your input.
I agree, it's probably not as big of a deal and would probably break more than it would fix.

Okay. I'll try to make it clear in the documentation.

Thanks for letting me know about the locale setting by the way. I didn't know this was a thing in C++.

Cheers
--Zuzu_Typ--
