### ISSUE TITLE
Broken `ivec3` access

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#76]
Hi again
I was trying to test your latest update (new vec and mat initializations) and I found this with `ivec3`
It seems that the saturation behavior changed:

old behavior (official 1.2.0)
```python
>>> v = ivec3(vec3(1,1,0) / 1e-13)
>>> v
ivec3( 1.131613+09, 1.131613+09, 0 )
>>> v[0]
1316134912
```
Well, okay, this result is not mathematically correct but it is actually usefull because the `1316134912` changes with the floating number truncated (there is no saturation).

current behavior (since #71 I think)
```python
>>> v = ivec3(vec3(1,1,0) / 1e-13)
>>> v
ivec3( -2.14748e+09, -2.14748e+09, 0 )
>>> v[0]
-2147483648
>>> tuple(v)
(-2147483648, -2147483648, 0)
```
This time the `-2147483648` is there each time the floating point number truncated is too huge

Don't know if the old behavior was intended (even if it's not the nominal usage of ints), but I was using it ;)
Did the memory layout changed ? Is it definitive ?

**Comment by Zuzu-Typ** [comment]
Hi there Jimy,

I honestly can't explain this one.
Technically, the "old behavior" is not intended. I didn't implement the conversion constructors before. Instead, the vec3 is interpreted as an iterable, which is simply converted to any other given type.

The new behavior is the same way that the original glm does it - I've actually tested this example and it provides the same result.

Actually, you get the same result on PyGLM 1.2.0.
The reason why the result appears to be different, because it was compiled using gcc and von MSVC.

That said, I don't really get why this is the result.
It is computed similarly to the following equasion:
```C++
double d = 10000000000000.0;
long l = (long)d;
```
The reason why we have a double here instead of a float, is because Python uses double precision floating point values as float.
Likewise, Python uses long values as int.

Unfortunately, the precision of longs isn't clearly defined in C++.
On MSVC it has 32bits.
on gcc it has 64 bits.

Glm uses a fixed size 32bit integer though. That's why there are compatibility issues between different compilers.

I don't know if there is a way to fix this.

Cheers

**Comment by Zuzu-Typ** [comment]
I've dug a little more into this and it's the casting operation that does the conversion.
See [here](https://docs.microsoft.com/en-us/cpp/c-language/conversions-from-floating-point-types?view=vs-2019).

> Casting double to int:
Truncate at decimal point. If result is too large to be represented as int, result is undefined.

So you can't rely on the result.

**Comment by jimy-byerley** [comment]
Ok thanks :)
The issue related to this was not difficult to fix in my case, but I wanted to know
