### ISSUE TITLE
Problems to compile with Intel (2018) compiler

### ISSUE THREAD

**Issue by SimonPinches** [Zuzu-Typ/PyGLM#79]
When I try to compile with the Intel `icc` compiler I get errors as follows:
```
    icc -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -O2 -axAVX,CORE-AVX2 -ftz -fp-speculation=safe -fp-model source -I/work/imas/opt/EasyBuild/software/imkl/2018.1.163-iimpi-2018a/mkl/include -fPIC -Ig
lm/ -I/work/imas/opt/EasyBuild/software/Python/3.6.4-intel-2018a/include/python3.6m -c PyGLM.cpp -o build/temp.linux-x86_64-3.6/PyGLM.o -std=c++11
    In file included from glm/glm/./ext/vector_bool2.hpp(5),
                     from glm/glm/vec2.hpp(5),
                     from glm/glm/glm.hpp(116),
                     from PyGLM.cpp(33):
    glm/glm/./ext/../detail/type_vec2.hpp(89): warning #3699: constexpr non-static member function will not be implicitly 'const' in C++14
                GLM_FUNC_DECL GLM_CONSTEXPR T& operator[](length_type i);
                              ^
    
    In file included from glm/glm/./ext/vector_bool2.hpp(5),
                     from glm/glm/vec2.hpp(5),
                     from glm/glm/glm.hpp(116),
                     from PyGLM.cpp(33):
    glm/glm/./ext/../detail/type_vec2.hpp(90): error: cannot overload functions distinguished by return type alone
                GLM_FUNC_DECL GLM_CONSTEXPR T const& operator[](length_type i) const;
                                                     ^
 ```
Any ideas how to fix? (It compiles fine with GCC).

**Comment by Zuzu-Typ** [comment]
Hi Simon,

PyGLM only officially supports three compilers: MSVC, GCC and clang - that's *officially*, because those are the only ones that are tested in CI.

However that doesn't mean it doesn't work on other compilers.

Apparently though, your compiler of choice is unable to build the [C++ version of glm](https://github.com/g-truc/glm).
glm [claims](https://github.com/g-truc/glm/blob/master/readme.md) to work on 
> Intel C++ Composer XE 2013 and higher
And any C++11 compiler

Yet, it doesn't seem to work with yours.

Unfortunately, the possibility of submitting issues to glm was removed, so it might not be possible to get your issue fixed.

**Comment by SimonPinches** [comment]
Thanks for your rapid response @Zuzu-Typ.  Perhaps @Groovounet (appears to be main developer of GLM) or @christophe-lunarg (author of the [readme ](https://github.com/g-truc/glm/blob/master/readme.md) you mention can help?  (Assuming mentions in different projects works!)
