### ISSUE TITLE
1.99 breaks glm.vec2() constructor when using numpy with explicit dtype

### ISSUE THREAD

**Issue by justaPCWingo** [Zuzu-Typ/PyGLM#84]
Hi,

Upgrading from pyGLM from 1.2.0 to 1.99 has broken initialization of vec2 objects when using numpy values of 32 bit precision.

This code snippet:
```python
import glm
import numpy as np
k = np.array([1.,2.],dtype=np.float32)
v=glm.vec2(k[0],k[1])
```

Produces the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid argument type(s) for vec()
```

**Comment by Zuzu-Typ** [comment]
Hi there,

thank you for letting me know about this issue.

The reason why this occurs is because ```np.array([1.,2.],dtype=np.float32)[0]``` returns an element of type `numpy.float32` - which is not a standard float type.
Previously I had been using [PyNumber_Check](https://docs.python.org/3/c-api/number.html#c.PyNumber_Check) to determine wether or not a given type can be converted to a a number or not - though that is not what this function is actually intended for. It only checks if the type supports numeric arithmetics or conversion of any sort, thus, glm types were also interpreted as numbers.
Hence I removed that functionality. 
I might have an idea to get it to work correctly though, so don't worry.

By the way, you should be able to simply do the following to achieve the same goal:
```Python
import glm
import numpy as np
k = np.array([1.,2.],dtype=np.float32)
v = glm.vec2(k) # <--
```

Cheers
--Zuzu_Typ--

**Comment by justaPCWingo** [comment]
Thanks for the quick response! That's good to know.

Indeed that solution appears that it would work. I'll make the necessary changes.

**Comment by Zuzu-Typ** [comment]
Dang. I should have tested the numpy buffer protocol before committing this.

Well due to the way NumPy's arrays are generalized, they all support being converted to float or int using `float(arr)` or `int(arr)` respectively, though that only works on arrays with only one single element.
This requires me to check, wether or not I can actually get a number from such a type or if it raises an exception.
Thus decreasing performance for numpy array to PyGLM type conversions.
