### ISSUE TITLE
use PyGLM in combination with Cython

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#93]
Hello !
Is there an easy way to use pyglm as an interface type for a cython module ?

For instance, I'm considering the specific case of having a cython function taking glm types as arguments and as return value.

 PyGLM is written in C++, binding a C++ template library whereas Cython is a C generator (It can also manage with C++ but templates can make it complicated). 
What would be the way to achieve this ?

**Comment by Zuzu-Typ** [comment]
Hello there @jimy-byerley,

unfortunately I don't have any experience with cython whatsoever and wasn't able to find a solution myself.

I'm sure it's possible somehow, though I fear I lack the necessary knowledge.

Maybe you'll have more luck over on StackOverflow?

Cheers
--Zuzu_Typ--

**Comment by jimy-byerley** [comment]
Hello dear @Zuzu-Typ, I know this thread is closed, but I have some news on this topic.

I finally managed to use pyglm together with cython !  I recently made a small module [arrex](https://github.com/jimy-byerley/arrex)  that provide dynamically typed lists using custom dtypes, including glm types.

### solution

Well it's not a really regular solution since it's not using any wrapper/declaration to transmit the glm objects to cython: The array is copying the content of the object for what remains after its `PyObject` header. 
So it relys on the current ABI of pyglm and cpython, however the used parts of their ABI are those that are not about to change soon (an `PyObject` header MUST be at the beginning, and a `glm::vec3<T>` is a packed C struct. Those are not gonna change).

An other interesting feature to share is: Thanks to the allocation/ownership strategy I used, it's perfectly safe to access the buffer of those arrays even while resizing the array.

### what do you say ?

Since I made this module mostly to work with glm types, I would be very happy to have your mind on it (if you have time and interest for it of course).

**Comment by Zuzu-Typ** [comment]
Hey there @jimy-byerley, 

I've taken a look at arrex a while ago and thought it was a neat idea (: 

I haven't been able to try it out myself though, because it doesn't seem to want to build on Windows with MSVC. I did get it to build on my Linux VM, but for some reason it still didn't work - but that might be do to some missing requirements or incorrect setup on my end.

When I've got more time, I'll try and see if I can get it to work, so I can actually check it out and give you a more detailed reply.

Don't worry by the way, you're not the only one who's doing some trickery.
One example:
My array class needs to be able to work with ctypes types. There is not any documented way of extracting the data from those types that I know of, but I've found out that the first part of ctypes objects is a pointer to it's data. By doing some more trickery to determine what type of data is actually stored in the buffer (e.g. double, int32, etc.), I extract the data right from the object, without the need of converting it using conventional methods.

I'm sure I could list you three or four more examples.

If the ABI ever changes, I'm screwed 😅
